name: saral_yatri
description: QR-based bus booking system for government buses
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  

  # HTTP Client
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # QR Code
  qr: ^3.0.2
  mobile_scanner: ^7.1.2

  # Dropdown
  animated_custom_dropdown: ^3.1.1

  # Location
  geolocator: ^10.1.0

  # Permissions
  permission_handler: ^11.2.0

  # Screen Protection
  screen_protector: ^1.4.2

  # Connectivity
  connectivity_plus: ^5.0.2

  # Logging
  dev_log: ^1.0.1

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  # flutter_local_notifications: ^19.4.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
