name: saral_yatri
description: QR-based bus booking system for government buses
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  

  # HTTP Client
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # QR Code
  qr: ^3.0.2
  mobile_scanner: ^7.1.2

  # Dropdown
  animated_custom_dropdown: ^3.1.1

  # Location
  geolocator: ^10.1.0

  # Permissions
  permission_handler: ^11.2.0

  # Screen Protection
  screen_protector: ^1.4.2

  # Connectivity
  connectivity_plus: ^5.0.2

  # Logging
  dev_log: ^1.0.1

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  # flutter_local_notifications: ^19.4.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^3.0.3
  
  # New dependencies for additional screens
  url_launcher: ^6.2.4
  package_info_plus: ^9.0.0
  image_picker: ^1.2.0

  # Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"
  
  # Code generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
